import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavigationBar from '@exchange-gateway/widgets/navigation-bar/NavigationBar';
import getSession from '@exchange-gateway/shared/authentication/get-session';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {session ? <header><NavigationBar /></header> : ''}
        {children}
      </body>
    </html>
  );
}
